all:
  hosts:
    secsys02:
      ansible_host: 10.28.55.2
    secsys03:
      ansible_host: 10.28.55.3
    mail:
      ansible_host: 10.28.55.4
    secsys05:
      ansible_host: 10.28.55.5
    secsys06:
      ansible_host: 10.28.55.6
    secsys07:
      ansible_host: 10.28.55.7
    secsys08:
      ansible_host: 10.28.55.8

  children:
    backend:
      hosts:
        secsys05:
      vars:
        ssh_specific_ldap_groups_backend:
          - "backend-admin"
    db:
      hosts:
        secsys05:
      vars:
        ssh_specific_ldap_groups_db:
          - "database-admin"
    db_backups:
      hosts:
        mail:
        secsys08:
    dns:
      hosts:
        secsys02:
        secsys08:
      vars:
        ssh_specific_ldap_groups_dns:
          - "dns-admin"
    docker:
      hosts:
        secsys02:
        secsys03:
        secsys05:
        secsys07:
    frontend:
      hosts:
        secsys03:
      vars:
        ssh_specific_ldap_groups_frontend:
          - "frontend-admin"
    ids:
      hosts:
        secsys06:
      vars:
        ssh_specific_ldap_groups_ids:
          - "ids-admin"
    ids-clients:
      hosts:
        secsys02:
        secsys03:
        mail:
        secsys05:
        secsys07:
        secsys08:
    keycloak:
      hosts:
        secsys07:
      vars:
        ssh_specific_ldap_groups_keycloak:
          - "keycloak-admin"
    mail:
      hosts:
        mail:
      vars:
        ssh_specific_ldap_groups_mail:
          - "mail-admin"
    pipeline:
      hosts:
        secsys02:
    revproxy:
      hosts:
        secsys03:
      vars:
        ssh_specific_ldap_groups_revproxy:
          - "revproxy-admin"

# Damit nicht alles gleichzeitig neustartet
    patch_group_a:
      hosts:
        secsys02:
        secsys06:
    patch_group_b:
      hosts:
        mail:
        secsys07:
    patch_group_c:
      hosts:
        secsys03:
        secsys05:
        secsys08: