---

hardening_logging_auditd_package_list:
  - auditd

hardening_logging_messages_file: "/var/log/syslog"
hardening_logging_auditd_syslog_plugin_path: "/etc/audit/plugins.d"
hardening_logging_auditd_conf_log_group: "adm"
hardening_logging_auditd_conf_disp_qos: false
hardening_logging_auditd_conf_dispatcher: false
hardening_logging_rsyslogd_conf_path: "/etc/rsyslog.d/50-default.conf"

# Section for: auditd
auditd_handler_name: "Restart auditd common"
hardening_logging_auditd_path: "/etc/audit"
hardening_logging_auditd_rules_path: "/etc/audit/rules.d"
# rules
hardening_logging_auditd_buffer_size: 8192
hardening_logging_auditd_immutable_flag: 1    # Set enabled flag. 0=disabled 1=enabled 2=immutable
# conf
hardening_logging_auditd_conf_local_events: "yes"
hardening_logging_auditd_conf_write_logs: "yes"
hardening_logging_auditd_conf_log_file: "/var/log/audit/audit.log"
# hardening_logging_auditd_conf_log_group: "root"    # above hardening_logging_dict_os_differences
hardening_logging_auditd_conf_log_format: "RAW"
hardening_logging_auditd_conf_flush: "INCREMENTAL_ASYNC"
hardening_logging_auditd_conf_freq: "50"
hardening_logging_auditd_conf_max_log_file: "10"
hardening_logging_auditd_conf_num_logs: "5"
hardening_logging_auditd_conf_priority_boost: "4"
# hardening_logging_auditd_conf_disp_qos: ''         # above hardening_logging_dict_os_differences
# hardening_logging_auditd_conf_dispatcher: ''       # above hardening_logging_dict_os_differences
hardening_logging_auditd_conf_name_format: "NONE"
hardening_logging_auditd_conf_max_log_file_action: "ROTATE"
hardening_logging_auditd_conf_space_left: "75"
hardening_logging_auditd_conf_space_left_action: "SYSLOG"
hardening_logging_auditd_conf_verify_email: "yes"
hardening_logging_auditd_conf_action_mail_acct: "root"
hardening_logging_auditd_conf_admin_space_left: "50"
hardening_logging_auditd_conf_admin_space_left_action: "SUSPEND"
hardening_logging_auditd_conf_disk_full_action: "SUSPEND"
hardening_logging_auditd_conf_disk_error_action: "SUSPEND"
hardening_logging_auditd_conf_use_libwrap: "yes"
hardening_logging_auditd_conf_tcp_listen_queue: "5"
hardening_logging_auditd_conf_tcp_max_per_addr: "1"
hardening_logging_auditd_conf_tcp_client_max_idle: "0"
hardening_logging_auditd_conf_distribute_network: "no"
hardening_logging_auditd_conf_enable_krb5: "no"

# Section for: rsyslogd
hardening_logging_rsyslogd_path: "/etc/rsyslog.d"
hardening_logging_rsyslogd_package_name: "rsyslog"

### Section: Customize syscall rules and file watches
hardening_logging_auditd_syscalls_list:
  - "-a always,exit -F arch=b64 -S adjtimex -S settimeofday -S clock_settime -F uid!=ntp -k time-change"
  - "-a always,exit -F arch=b64 -S clock_settime -F a0=0 -k time-change"
  - "-a always,exit -F arch=b64 -S sethostname -S setdomainname -k network_modifications"
  - "-a always,exit -F arch=b64 -S chmod -S fchmod -S fchmodat -S chown -S fchown -S lchown -S fchownat -S setxattr -S lsetxattr -S fsetxattr -S removexattr -S lremovexattr -S fremovexattr -F auid>=1000 -F auid!=4294967295 -k perm_mod"  # noqa: yaml[line-length]
  - "-a always,exit -F arch=b64 -S creat -S open -S openat -S truncate -S open_by_handle_at -S ftruncate -F exit=-EACCES -F auid>=1000 -F auid!=4294967295 -k file_access"  # noqa: yaml[line-length]
  - "-a always,exit -F arch=b64 -S creat -S open -S openat -S truncate -S open_by_handle_at -S ftruncate -F exit=-EPERM -F auid>=1000 -F auid!=4294967295 -k file_access"  # noqa: yaml[line-length]
  - "-a always,exit -F arch=b64 -S mkdir -S creat -S link -S symlink -S mknod -S mknodat -S linkat -S symlinkat -F exit=-EACCES -k file_creation"
  - "-a always,exit -F arch=b64 -S mkdir -S link -S symlink -S mkdirat -F exit=-EPERM -k file_creation"
  - "-a always,exit -F arch=b64 -S rename -S renameat -S truncate -S chmod -S setxattr -S lsetxattr -S removexattr -S lremovexattr -F exit=-EPERM -k file_modification"  # noqa: yaml[line-length]
  - "-a always,exit -F arch=b64 -S mount -S umount2 -F auid!=4294967295 -k export"
  - "-a always,exit -F arch=b64 -S unlink -S unlinkat -S rename -S renameat -S rmdir -F auid>=1000 -F auid!=4294967295 -k delete"
  - "-a always,exit -F arch=b64 -S ptrace -k tracing"
  - "-a always,exit -F arch=b64 -S ptrace -F a0=4 -k code-injection"
  - "-a always,exit -F arch=b64 -S ptrace -F a0=5 -k data-injection"
  - "-a always,exit -F arch=b64 -S ptrace -F a0=6 -k register-injection"
  - "-a always,exit -F arch=b64 -S personality -F a0!=4294967295 -k bypass"
  - "-a always,exit -F arch=b64 -S delete_module -S init_module -S finit_module -k modules"
  - "-a always,exit -F arch=b64 -S execve -F path=/sbin/reboot -k systemevents"
  - "-a always,exit -F arch=b64 -S execve -F path=/sbin/poweroff -k systemevents"
  - "-a always,exit -F arch=b64 -S execve -F path=/sbin/shutdown -k systemevents"
  - "-a always,exit -F arch=b64 -S mknod -S mknodat -k specialfiles"
  - "-a always,exit -F arch=b64 -S swapon -S swapoff -k swap"
  - "-a always,exit -F arch=b64 -S open -F dir=/etc -F success=0 -k unauthedfileaccess"
  - "-a always,exit -F arch=b64 -S open -F dir=/bin -F success=0 -k unauthedfileaccess"
  - "-a always,exit -F arch=b64 -S open -F dir=/sbin -F success=0 -k unauthedfileaccess"
  - "-a always,exit -F arch=b64 -S open -F dir=/usr/bin -F success=0 -k unauthedfileaccess"
  - "-a always,exit -F arch=b64 -S open -F dir=/usr/sbin -F success=0 -k unauthedfileaccess"
  - "-a always,exit -F arch=b64 -S open -F dir=/var -F success=0 -k unauthedfileaccess"
  - "-a always,exit -F arch=b64 -S open -F dir=/home -F success=0 -k unauthedfileaccess"
  - "-a always,exit -F arch=b64 -S open -F dir=/srv -F success=0 -k unauthedfileaccess"

hardening_logging_auditd_filewatches_list:
  - "/var/log/audit/ rwxa auditlog"
  - "/etc/audit/ wa auditconfig"
  - "/etc/libaudit.conf wa auditconfig"
  - "/etc/audisp/ wa audispconfig"
  - "/sbin/auditctl x audittools"
  - "/sbin/auditd x audittools"
  - "/usr/sbin/augenrules x audittools"
  - "/etc/rsyslog.conf wa syslogconfig"
  - "/etc/rsyslog.d/ wa syslogconfig"
  - "/etc/syslog-ng/syslog-ng.conf wa syslogconfig"
  - "/etc/sysctl.conf wa sysctl"
  - "/etc/sysctl.d wa sysctl"
  - "/etc/modprobe.conf wa modprobe"
  - "/etc/modprobe.d wa modprobe"
  - "/etc/localtime wa time-change"
  - "/usr/sbin/stunnel x stunnel"
  - "/usr/bin/stunnel x stunnel"
  - "/etc/cron.allow wa scheduled-tasks"
  - "/etc/cron.deny wa scheduled-tasks"
  - "/etc/cron.d/ wa scheduled-tasks"
  - "/etc/cron.daily/ wa scheduled-tasks"
  - "/etc/cron.hourly/ wa scheduled-tasks"
  - "/etc/cron.monthly/ wa scheduled-tasks"
  - "/etc/cron.weekly/ wa scheduled-tasks"
  - "/etc/crontab wa scheduled-tasks"
  - "/var/spool/cron/ rwxa scheduled-tasks"
  - "/etc/anacrontab rwxa scheduled-task"
  - "/etc/at.allow rwxa scheduled-task"
  - "/etc/at.deny rwxa scheduled-task"
  - "/var/spool/at rwxa scheduled-task"
  - "/etc/group wa identity"
  - "/etc/passwd wa identity"
  - "/etc/gshadow rwxa identity"
  - "/etc/shadow rwxa identity"
  - "/etc/security/opasswd rwxa identity"
  - "/etc/sudoers wa actions"
  - "/etc/sudoers.d/ wa actions"
  - "/usr/bin/passwd x passwd_modification"
  - "/usr/sbin/groupadd x group_modification"
  - "/usr/sbin/groupmod x group_modification"
  - "/usr/sbin/addgroup x group_modification"
  - "/usr/sbin/useradd x user_modification"
  - "/usr/sbin/userdel x user_modification"
  - "/usr/sbin/usermod x user_modification"
  - "/usr/sbin/adduser x user_modification"
  - "/etc/login.defs wa login"
  - "/etc/securetty wa login"
  - "/var/log/faillog wa login"
  - "/var/log/lastlog wa login"
  - "/var/log/tallylog wa login"
  - "/var/run/faillock/ wa login"
  - "/etc/hosts wa network_modifications"
  - "/etc/sysconfig/network wa network_modifications"
  - "/etc/sysconfig/network-scripts w network_modifications"
  - "/etc/networks wa network_modifications"
  - "/etc/nsswitch.conf rwxa network_modifications"
  - "/etc/issue wa etcissue"
  - "/etc/issue.net wa etcissue"
  - "/etc/inittab wa init"
  - "/etc/init.d/ wa init"
  - "/etc/init/ wa init"
  - "/etc/ld.so.conf wa libpath"
  - "/etc/ld.so.conf.d wa libpath"
  - "/etc/ld.so.preload wa systemwide_preloads"
  - "/etc/pam.d/ wa pam"
  - "/etc/security/limits.conf wa pam"
  - "/etc/security/limits.d wa pam"
  - "/etc/security/pam_env.conf wa pam"
  - "/etc/security/namespace.conf wa pam"
  - "/etc/security/namespace.d wa pam"
  - "/etc/security/namespace.init wa pam"
  - "/etc/aliases wa mail"
  - "/etc/postfix/ wa mail"
  - "/etc/exim4/ wa mail"
  - "/etc/ssh/sshd_config rwxa sshd"
  - "/etc/ssh/sshd_config.d rwxa sshd"
  - "/root/.ssh wa rootkey"
  - "/bin/systemctl x systemd"
  - "/etc/systemd/ wa systemd"
  - "/etc/selinux/ wa mac_policy"
  - "/usr/share/selinux/ wa mac_policy"
  - "/bin/su x priv_esc"
  - "/usr/bin/sudo x priv_esc"
  - "/etc/sudoers rw priv_esc"
  - "/etc/sudoers.d rw priv_esc"
  - "/sbin/shutdown x power"
  - "/sbin/poweroff x power"
  - "/sbin/reboot x power"
  - "/sbin/halt x power"
  - "/var/run/utmp wa session"
  - "/var/log/btmp wa session"
  - "/var/log/wtmp wa session"
  - "/usr/bin/whoami x recon"
  - "/usr/bin/id x recon"
  - "/bin/hostname x recon"
  - "/bin/uname x recon"
  - "/etc/issue r recon"
  - "/etc/hostname r recon"
  - "/usr/bin/wget x susp_activity"
  - "/usr/bin/curl x susp_activity"
  - "/usr/bin/base64 x susp_activity"
  - "/bin/nc x susp_activity"
  - "/bin/netcat x susp_activity"
  - "/usr/bin/ncat x susp_activity"
  - "/usr/bin/ssh x susp_activity"
  - "/usr/bin/scp x susp_activity"
  - "/usr/bin/sftp x susp_activity"
  - "/usr/bin/ftp x susp_activity"
  - "/usr/bin/socat x susp_activity"
  - "/usr/bin/wireshark x susp_activity"
  - "/usr/bin/tshark x susp_activity"
  - "/usr/bin/rawshark x susp_activity"
  - "/usr/bin/rdesktop x susp_activity"
  - "/usr/bin/nmap x susp_activity"
  - "/bin/nc.openbsd x susp_activity"
  - "/bin/nc.traditional x susp_activity"
  - "/sbin/iptables x sbin_susp"
  - "/sbin/ip6tables x sbin_susp"
  - "/sbin/ifconfig x sbin_susp"
  - "/usr/sbin/arptables x sbin_susp"
  - "/usr/sbin/ebtables x sbin_susp"
  - "/sbin/xtables-nft-multi x sbin_susp"
  - "/usr/sbin/nft x sbin_susp"
  - "/usr/sbin/tcpdump x sbin_susp"
  - "/usr/sbin/traceroute x sbin_susp"
  - "/usr/sbin/ufw x sbin_susp"
  - "/etc/profile.d/ wa shell_profiles"
  - "/etc/profile wa shell_profiles"
  - "/etc/shells wa shell_profiles"
  - "/etc/bashrc wa shell_profiles"
  - "/etc/csh.cshrc wa shell_profiles"
  - "/etc/csh.login wa shell_profiles"
  - "/etc/fish/ wa shell_profiles"
  - "/etc/zsh/ wa shell_profiles"
  - "/usr/bin/rpm x software_mgmt"
  - "/usr/bin/yum x software_mgmt"
  - "/usr/bin/dnf x software_mgmt"
  - "/sbin/yast x software_mgmt"
  - "/sbin/yast2 x software_mgmt"
  - "/bin/rpm x software_mgmt"
  - "/usr/bin/zypper x software_mgmt"
  - "/usr/bin/dpkg x software_mgmt"
  - "/usr/bin/apt x software_mgmt"
  - "/usr/bin/apt-add-repository x software_mgmt"
  - "/usr/bin/apt-get x software_mgmt"
  - "/usr/bin/aptitude x software_mgmt"
  - "/usr/bin/wajig x software_mgmt"
  - "/usr/bin/snap x software_mgmt"
  - "/usr/bin/pip x software_mgmt"
  - "/usr/bin/pip3 x software_mgmt"
  - "/etc/puppetlabs/puppet/ssl wa puppet_ssl"
  - "/etc/chef wa soft_chef"
