---
- name: Run Tasks for System Hardening
  ansible.builtin.include_tasks: 20_system_hardening.yml

- name: Run Tasks for Network Hardening
  ansible.builtin.include_tasks: 21_network_hardening.yml

- name: Run Tasks for User Authentication
  ansible.builtin.include_tasks: 23_user_authentication.yml

- name: Run Tasks for Logging
  ansible.builtin.include_tasks: 30_logging.yml

- name: Run Tasks for IPV6-Hardening
  ansible.builtin.include_tasks: 31_ipv6_hardening_grub.yml

- name: Run Tasks for Auditd (Req 40 - 46) + External Logging (Req 47 - 48) + RSyslog
  ansible.builtin.include_role:
    name: hardening_logging

- name: Run Tasks for PAM (Pluggable Authentication Modules)
  ansible.builtin.include_role:
    name: hardening_pam

- name: Run Tasks for Mandatory Access Control (AppArmor)
  ansible.builtin.include_tasks: 62_apparmor.yml

- name: Run Tasks for Firewall
  ansible.builtin.include_tasks: 63_ufw_firewall.yml

- name: Run Tasks for Regular Compliance Checks
  ansible.builtin.include_tasks: 70_compliance_check.yml
  when:
    - hardening_linux_use_cc
