- name: Docker APT-Key hinzufügen
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: "{{ keyrings_dir }}/docker.asc"
    mode: '0644'

- name: Docker APT-Repo hinzufügen
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64 signed-by={{ keyrings_dir }}/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present
    update_cache: yes

- name: Docker installieren
  ansible.builtin.apt:
    pkg: "{{ docker_packages}}"
    state: present