- name: Check, ob benötigte Vars gesetzt wurden
  ansible.builtin.assert:
    that:
      - ssl_file_owner
      - ssl_common_name
      - ssl_selected_server
      - ssl_dest_dir
      - ssl_cert_validity_duration
      - ssl_key_usage_list
      - ssl_extended_key_usage_list
      - ssl_subject_alt_name_list
    fail_msg: "Nicht alle benötigten Vars für das Playbook wurden gesetzt"

- name: Check, ob auf dem Server bereits ein valides Cert mit dem Namen liegt
  delegate_to: "{{ ssl_selected_server }}"
  run_once: true
  ansible.builtin.command:
    cmd: "openssl x509 -checkend {{ ssl_role_cert_validity_check }} -noout -in {{ ssl_dest_dir }}/{{ ssl_cert_file_name }}"
  ignore_errors: true
  register: cert_check

- name: Generiert neues Cert, wenn altes nicht existiert oder bald abläuft
  ansible.builtin.include_tasks: generate.yml
  when: cert_check is not defined or cert_check.rc is not defined or cert_check.rc != 0
